services:
  - type: web
    name: hanuman-sports
    env: node
    region: singapore
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && node server.js
    healthCheckPath: /api/products
    envVars:
      - key: PORT
        value: 10000
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
